# Generated by Django 3.2.7 on 2021-10-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='RollNo',
            new_name='rollno',
        ),
    ]
